### ISSUE TITLE
Помянем

### ISSUE THREAD

**Issue by GorgeousPuree** [nikmaxim/TransactionAppExpress#1]
![image](https://user-images.githubusercontent.com/46875481/187245440-e3495d92-b2b1-46dc-ab15-96a5f97eb37d.png)

**Comment by nikmaxim** [comment]
![Без названия](https://user-images.githubusercontent.com/39594384/187249815-2261a752-c7ab-4f2a-92e7-edda9c3b0e88.jpg)
